In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report

ModuleNotFoundError: No module named 'pandas'

In [3]:
df = pd.read_csv(r"C:\Users\Yagnesh Narola\Documents\Coding Languages\Artificial Intelegence\Excel_and_CSV\hotel bookings decision tree.csv")

In [ ]:
df

hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015   
1       Resort Hotel            0        737               2015   
2       Resort Hotel            0          7               2015   
3       Resort Hotel            0         13               2015   
4       Resort Hotel            0         14               2015   
...              ...          ...        ...                ...   
119385    City Hotel            0         23               2017   
119386    City Hotel            0        102               2017   
119387    City Hotel            0         34               2017   
119388    City Hotel            0        109               2017   
119389    City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
0                    July                        27   
1                    July                        27   
2                    July                        27   
3                    July                        27   
4                    July                        27   
...                   ...                       ...   
119385             August                        35   
119386             August                        35   
119387             August                        35   
119388             August                        35   
119389             August                        35   

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0   
1                               1                        0   
2                               1                        0   
3                               1                        0   
4                               1                        0   
...                           ...                      ...   
119385                         30                        2   
119386                         31                        2   
119387                         31                        2   
119388                         31                        2   
119389                         29                        2   

        stays_in_week_nights  adults  ...  deposit_type  agent company  \
0                          0       2  ...    No Deposit    NaN     NaN   
1                          0       2  ...    No Deposit    NaN     NaN   
2                          1       1  ...    No Deposit    NaN     NaN   
3                          1       1  ...    No Deposit  304.0     NaN   
4                          2       2  ...    No Deposit  240.0     NaN   
...                      ...     ...  ...           ...    ...     ...   
119385                     5       2  ...    No Deposit  394.0     NaN   
119386                     5       3  ...    No Deposit    9.0     NaN   
119387                     5       2  ...    No Deposit    9.0     NaN   
119388                     5       2  ...    No Deposit   89.0     NaN   
119389                     7       2  ...    No Deposit    9.0     NaN   

       days_in_waiting_list customer_type     adr  \
0                         0     Transient    0.00   
1                         0     Transient    0.00   
2                         0     Transient   75.00   
3                         0     Transient   75.00   
4                         0     Transient   98.00   
...                     ...           ...     ...   
119385                    0     Transient   96.14   
119386                    0     Transient  225.43   
119387                    0     Transient  157.71   
119388                    0     Transient  104.40   
119389                    0     Transient  151.20   

        required_car_parking_spaces  total_of_special_requests  \
0                                 0                          0   
1                                 0                          0   
2                                 0                          0   
3             

In [5]:
pd.set_option('display.max_columns',None)

In [ ]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [7]:
df['is_canceled'].unique()

array([0, 1], dtype=int64)

In [8]:
df.shape

(119390, 32)

In [9]:
df = df.drop(columns = ['company','reservation_status', 'reservation_status_date','country','agent'])

In [10]:
# df['country'] = df['country'].astype(str)
# df['country'] = df['country'].replace('NaN',None)
# df['country'] = df['country'].fillna(df['country'].mode()[0])
# type(df['country'])
# df['country']

In [11]:
df['children'].unique()

array([ 0.,  1.,  2., 10.,  3., nan])

In [12]:
df['children'] = pd.to_numeric(df['children'],errors = 'coerce')

In [13]:
df['children'] = df['children'].fillna(df['children'].median())

In [14]:
le = LabelEncoder()
le

LabelEncoder()

In [15]:
catcol = ['hotel', 'arrival_date_month', 'meal', 
                       'market_segment', 'distribution_channel', 
                       'reserved_room_type', 'assigned_room_type', 
                       'deposit_type', 'customer_type']

In [16]:
for i in df[catcol]:
    df[i] = le.fit_transform(df[i])

In [17]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
dtype: int64

In [18]:
df = df.drop(columns = catcol)

In [19]:
df = pd.concat([df.reset_index(drop=True),encoded_df.reset_index(drop=True)],axis = 1)

NameError: name 'encoded_df' is not defined

In [427]:
model = tree.DecisionTreeClassifier()

In [429]:
x = df.drop(columns = 'is_canceled')
y = df['is_canceled']

In [430]:
y.unique()

array([0, 1], dtype=int64)

In [431]:
model = DecisionTreeClassifier(criterion = "entropy", random_state = 42)
model

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [432]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [433]:
model.fit(xtrain, ytrain)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [434]:
pred = model.predict(x_test)
pred

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- agent


In [ ]:
model.score(xtest,ytest)

0.8352039534299355

In [ ]:
classification_report(ytest, pred)

'              precision    recall  f1-score   support\n\n           0       0.87      0.87      0.87     14907\n           1       0.78      0.78      0.78      8971\n\n    accuracy                           0.84     23878\n   macro avg       0.82      0.82      0.82     23878\nweighted avg       0.84      0.84      0.84     23878\n'

In [386]:
test_data = df.drop('is_canceled')

KeyError: "['is_canceled'] not found in axis"

In [ ]:
test_data

lead_time  arrival_date_year  arrival_date_week_number  \
0        342               2015                        27   

   arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  \
0                          1                        0                     0   

   adults  children  babies  is_repeated_guest  previous_cancellations  \
0       2       0.0       0                  0                       0   

   previous_bookings_not_canceled  booking_changes  agent  \
0                               0                3   14.0   

   days_in_waiting_list  adr  required_car_parking_spaces  \
0                     0  0.0                            0   

   total_of_special_requests  hotel_0  hotel_1  arrival_date_month_0  \
0                          0      0.0      1.0                   0.0   

   arrival_date_month_1  arrival_date_month_2  arrival_date_month_3  \
0                   0.0                   0.0                   0.0   

   arrival_date_month_4  arrival_date_month_5  arrival_date_month_6  \
0                   0.0                   1.0                   0.0   

   arrival_date_month_7  arrival_date_month_8  arrival_date_month_9  \
0                   0.0                   0.0                   0.0   

   arrival_date_month_10  arrival_date_month_11  meal_0  meal_1  meal_2  \
0                    0.0                    0.0     1.0     0.0     0.0   

   meal_3  meal_4  market_segment_0  market_segment_1  market_segment_2  \
0     0.0     0.0               0.0               0.0               0.0   

   market_segment_3  market_segment_4  market_segment_5  market_segment_6  \
0               1.0               0.0               0.0               0.0   

   market_segment_7  distribution_channel_0  distribution_channel_1  \
0               0.0                     0.0                     1.0   

   distribution_channel_2  distribution_channel_3  distribution_channel_4  \
0                     0.0                     0.0                     0.0   

   reserved_room_type_0  reserved_room_type_1  reserved_room_type_2  \
0                   0.0                   0.0                   1.0   

   reserved_room_type_3  reserved_room_type_4  reserved_room_type_5  \
0                   0.0                   0.0                   0.0   

   reserved_room_type_6  reserved_room_type_7  reserved_room_type_8  \
0                   0.0                   0.0                   0.0   

   reserved_room_type_9  assigned_room_type_0  assigned_room_type_1  \
0                   0.0                   0.0                   0.0   

   assigned_room_type_2  assigned_room_type_3  assigned_room_type_4  \
0                   1.0                   0.0                   0.0   

   assigned_room_type_5  assigned_room_type_6  assigned_room_type_7  \
0                   0.0                   0.0                   0.0   

   assigned_room_type_8  assigned_room_type_9  assigned_room_type_10  \
0                   0.0                   0.0                    0.0   

   assigned_room_type_11  deposit_type_0  deposit_type_1  deposit_type_2  \
0                    0.0             1.0             0.0             0.0   

   customer_type_0  customer_type_1  customer_type_2  customer_type_3  
0              0.0              0.0              1.0              0.0

In [383]:
pred = model.predict(test_data)
pred

array([1], dtype=int64)

In [384]:
inv = le.inverse_transform(pred)
print("Prediction Booking Canceled?:",inv[0])

Prediction Booking Canceled?: Group


In [385]:
inv

array(['Group'], dtype=object)