In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import pickle as pk

In [3]:
df = pd.read_csv(r'C:\Users\Yagnesh Narola\Documents\Coding Languages\Artificial Intelegence\Data Analysis\Excel_and_CSV\loan_approval_dataset.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   loan_id                    4269 non-null   int64 
 1    no_of_dependents          4269 non-null   int64 
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64 
 5    loan_amount               4269 non-null   int64 
 6    loan_term                 4269 non-null   int64 
 7    cibil_score               4269 non-null   int64 
 8    residential_assets_value  4269 non-null   int64 
 9    commercial_assets_value   4269 non-null   int64 
 10   luxury_assets_value       4269 non-null   int64 
 11   bank_asset_value          4269 non-null   int64 
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB


In [5]:
df.isnull().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [6]:
df.head()

loan_id   no_of_dependents      education  self_employed   income_annum  \
0        1                  2       Graduate             No        9600000   
1        2                  0   Not Graduate            Yes        4100000   
2        3                  3       Graduate             No        9100000   
3        4                  3       Graduate             No        8200000   
4        5                  5   Not Graduate            Yes        9800000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   
3      30700000           8           467                   18200000   
4      24200000          20           382                   12400000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  17600000              22700000            8000000   
1                   2200000               8800000            3300000   
2                   4500000              33300000           12800000   
3                   3300000              23300000            7900000   
4                   8200000              29400000            5000000   

   loan_status  
0     Approved  
1     Rejected  
2     Rejected  
3     Rejected  
4     Rejected

In [7]:
df.drop(columns = 'loan_id', inplace = True)

In [8]:
df.shape

(4269, 12)

In [9]:
df.columns = df.columns.str.strip()
df.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [10]:
df['Assets'] = df['residential_assets_value'] + df['commercial_assets_value'] + df['luxury_assets_value'] + df['bank_asset_value']

In [11]:
df = df.drop(columns = ['residential_assets_value' , 'commercial_assets_value' , 'luxury_assets_value' , 'bank_asset_value'])

In [12]:
df['education'].unique

<bound method Series.unique of 0            Graduate
1        Not Graduate
2            Graduate
3            Graduate
4        Not Graduate
            ...      
4264         Graduate
4265     Not Graduate
4266     Not Graduate
4267     Not Graduate
4268         Graduate
Name: education, Length: 4269, dtype: object>

In [13]:
df['education'] = df['education'].apply(lambda x:x.strip())

In [14]:
df['education'] = df['education'].replace(['Graduate','Not Graduate'],[1,0])

C:\Users\Yagnesh Narola\AppData\Local\Temp\ipykernel_3684\1218203024.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['education'] = df['education'].replace(['Graduate','Not Graduate'],[1,0])


In [15]:
df

no_of_dependents  education self_employed  income_annum  loan_amount  \
0                    2          1            No       9600000     29900000   
1                    0          0           Yes       4100000     12200000   
2                    3          1            No       9100000     29700000   
3                    3          1            No       8200000     30700000   
4                    5          0           Yes       9800000     24200000   
...                ...        ...           ...           ...          ...   
4264                 5          1           Yes       1000000      2300000   
4265                 0          0           Yes       3300000     11300000   
4266                 2          0            No       6500000     23900000   
4267                 1          0            No       4100000     12800000   
4268                 1          1            No       9200000     29700000   

      loan_term  cibil_score loan_status    Assets  
0            12          778    Approved  50700000  
1             8          417    Rejected  17000000  
2            20          506    Rejected  57700000  
3             8          467    Rejected  52700000  
4            20          382    Rejected  55000000  
...         ...          ...         ...       ...  
4264         12          317    Rejected   7400000  
4265         20          559    Approved  20000000  
4266         18          457    Rejected  39000000  
4267          8          780    Approved  28800000  
4268         10          607    Approved  77300000  

[4269 rows x 9 columns]

In [16]:
df['self_employed'] = df['self_employed'].apply(lambda x:x.strip())

In [17]:
df['self_employed'] = df['self_employed'].replace(['Yes','No'],[1,0])

C:\Users\Yagnesh Narola\AppData\Local\Temp\ipykernel_3684\3331251784.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['self_employed'] = df['self_employed'].replace(['Yes','No'],[1,0])


In [18]:
df['loan_status'] = df['loan_status'].apply(lambda x:x.strip())

In [19]:
df['loan_status'] = df['loan_status'].replace(['Approved','Rejected'],[1,0]) 

C:\Users\Yagnesh Narola\AppData\Local\Temp\ipykernel_3684\1237930702.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['loan_status'] = df['loan_status'].replace(['Approved','Rejected'],[1,0])


In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   no_of_dependents  4269 non-null   int64
 1   education         4269 non-null   int64
 2   self_employed     4269 non-null   int64
 3   income_annum      4269 non-null   int64
 4   loan_amount       4269 non-null   int64
 5   loan_term         4269 non-null   int64
 6   cibil_score       4269 non-null   int64
 7   loan_status       4269 non-null   int64
 8   Assets            4269 non-null   int64
dtypes: int64(9)
memory usage: 300.3 KB


In [21]:
X = df.drop(columns = 'loan_status')
y = df['loan_status']

In [22]:
xtrain, xtest, ytrain, ytest = train_test_split(X,y,test_size=0.2,random_state=42)

In [23]:
scalar = StandardScaler()
scalar

StandardScaler()

In [24]:
xtrainscaled = scalar.fit_transform(xtrain)
xtestscaled = scalar.fit_transform(xtest)

In [25]:
xtestscaled

array([[ 1.34468623,  0.98835816, -0.97684871, ...,  1.62098297,
        -1.0129156 ,  0.36040341],
       [-0.45337542,  0.98835816, -0.97684871, ..., -0.49895494,
         0.00215435,  0.31913368],
       [ 0.14597846,  0.98835816, -0.97684871, ...,  0.56101401,
        -0.84565975,  1.18579807],
       ...,
       [ 1.34468623, -1.01177897,  1.02369997, ..., -1.20560091,
         0.55582887,  0.18500704],
       [ 0.74533235, -1.01177897, -0.97684871, ...,  1.62098297,
        -1.30128774, -1.02213265],
       [-1.05272931, -1.01177897, -0.97684871, ..., -0.85227793,
        -0.43617131, -0.74872067]])

In [26]:
xtrainscaled

array([[ 1.51250774, -1.00263891, -1.01504731, ..., -0.86000338,
        -0.18740061,  0.60112728],
       [-1.43500078, -1.00263891,  0.98517575, ...,  0.1888936 ,
         0.63739678,  2.42870384],
       [-0.84549907,  0.99736803, -1.01504731, ..., -0.51037106,
         0.47476068, -1.31347672],
       ...,
       [ 0.92300603, -1.00263891,  0.98517575, ...,  0.88815826,
        -0.87860405,  1.17448463],
       [-0.25599737, -1.00263891,  0.98517575, ...,  0.1888936 ,
        -0.34422828,  0.09432034],
       [ 0.92300603,  0.99736803, -1.01504731, ..., -0.86000338,
         1.37506769,  0.66767769]])

In [27]:
model = LogisticRegression()
model

LogisticRegression()

In [28]:
model.fit(xtrainscaled,ytrain)

LogisticRegression()

In [29]:
model.score(xtestscaled,ytest)

0.905152224824356

In [30]:
model.predict(xtestscaled)

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,

In [31]:
df.head()

no_of_dependents  education  self_employed  income_annum  loan_amount  \
0                 2          1              0       9600000     29900000   
1                 0          0              1       4100000     12200000   
2                 3          1              0       9100000     29700000   
3                 3          1              0       8200000     30700000   
4                 5          0              1       9800000     24200000   

   loan_term  cibil_score  loan_status    Assets  
0         12          778            1  50700000  
1          8          417            0  17000000  
2         20          506            0  57700000  
3          8          467            0  52700000  
4         20          382            0  55000000

In [32]:
pred = pd.DataFrame([['2','1','0','9600000','29900000','12','778','50700000']],columns=['no_of_dependents','education','self_employed',	'income_annum', 'loan_amount', 'loan_term', 'cibil_score', 'Assets'])

In [33]:
pred

no_of_dependents education self_employed income_annum loan_amount loan_term  \
0                2         1             0      9600000    29900000        12   

  cibil_score    Assets  
0         778  50700000

In [34]:
pred = scalar.transform(pred)

In [35]:
pred

array([[-0.45337542,  0.98835816, -0.97684871,  1.63340716,  1.6669833 ,
         0.20769103,  1.03452662,  0.93817968]])

In [36]:
model.predict(pred)

array([1], dtype=int64)

In [37]:
pk.dump(model,open('model.pkl','wb'))
pk.dump(scalar,open('scaler.pkl','wb'))

In [38]:
pred

array([[-0.45337542,  0.98835816, -0.97684871,  1.63340716,  1.6669833 ,
         0.20769103,  1.03452662,  0.93817968]])